// ============================================================
// IFFCO GET Mock Test – Question Bank (4 Sets × 100 Questions)
// ============================================================

const ALL_MOCK_SETS = [

// ====================== MOCK TEST 1 ======================
[
// --- Data Structures (Q1-15) ---
{q:"What is the time complexity of searching an element in a balanced Binary Search Tree?",o:["O(n)","O(log n)","O(n log n)","O(1)"],a:1,s:"Technical – Data Structures"},
{q:"Which data structure is used for implementing recursion?",o:["Queue","Stack","Array","Linked List"],a:1,s:"Technical – Data Structures"},
{q:"The number of edges in a complete graph with n vertices is:",o:["n(n-1)","n(n-1)/2","n²","2n-1"],a:1,s:"Technical – Data Structures"},
{q:"Which traversal of a Binary Search Tree gives elements in sorted order?",o:["Preorder","Postorder","Inorder","Level order"],a:2,s:"Technical – Data Structures"},
{q:"What is the worst-case time complexity of Quick Sort?",o:["O(n log n)","O(n²)","O(n)","O(log n)"],a:1,s:"Technical – Data Structures"},
{q:"A queue is implemented using a singly linked list. The time complexity of enqueue and dequeue operations is:",o:["O(1) and O(n)","O(1) and O(1)","O(n) and O(1)","O(n) and O(n)"],a:1,s:"Technical – Data Structures"},
{q:"Which of the following is NOT a stable sorting algorithm?",o:["Merge Sort","Bubble Sort","Insertion Sort","Selection Sort"],a:3,s:"Technical – Data Structures"},
{q:"The height of a complete binary tree with n nodes is:",o:["log₂(n)","log₂(n+1)","⌊log₂(n)⌋","n-1"],a:2,s:"Technical – Data Structures"},
{q:"Which data structure is best suited for implementing a priority queue?",o:["Stack","Queue","Heap","Linked List"],a:2,s:"Technical – Data Structures"},
{q:"In a max-heap, the maximum element is always at:",o:["Any leaf node","The last node","The root","The middle level"],a:2,s:"Technical – Data Structures"},
{q:"What is the space complexity of Merge Sort?",o:["O(1)","O(log n)","O(n)","O(n²)"],a:2,s:"Technical – Data Structures"},
{q:"Which of the following is used in a Breadth-First Search (BFS)?",o:["Stack","Queue","Priority Queue","Deque"],a:1,s:"Technical – Data Structures"},
{q:"A circular queue of size n can hold a maximum of how many elements?",o:["n","n-1","n+1","2n"],a:1,s:"Technical – Data Structures"},
{q:"The postfix expression for the infix expression A + B * C is:",o:["AB+C*","ABC*+","ABC+*","A+BC*"],a:1,s:"Technical – Data Structures"},
{q:"Which of the following is an application of a stack?",o:["CPU scheduling","Parentheses matching","Level order traversal","Shortest path finding"],a:1,s:"Technical – Data Structures"},

// --- Algorithms (Q16-25) ---
{q:"What is the time complexity of binary search in a sorted array?",o:["O(n)","O(log n)","O(n²)","O(1)"],a:1,s:"Technical – Algorithms"},
{q:"Dijkstra's algorithm is used for finding:",o:["Minimum spanning tree","Shortest path from a single source","Maximum flow","Topological sort"],a:1,s:"Technical – Algorithms"},
{q:"Which algorithm design paradigm does Merge Sort follow?",o:["Greedy","Dynamic Programming","Divide and Conquer","Backtracking"],a:2,s:"Technical – Algorithms"},
{q:"The recurrence relation T(n) = 2T(n/2) + n gives a time complexity of:",o:["O(n)","O(n log n)","O(n²)","O(log n)"],a:1,s:"Technical – Algorithms"},
{q:"Which of the following problems is NP-Complete?",o:["Sorting","Shortest Path","Travelling Salesman Problem","Binary Search"],a:2,s:"Technical – Algorithms"},
{q:"Kruskal's algorithm is used for:",o:["Shortest path","Minimum spanning tree","Maximum flow","Graph coloring"],a:1,s:"Technical – Algorithms"},
{q:"The amortized time complexity of insertion in a dynamic array is:",o:["O(n)","O(1)","O(log n)","O(n²)"],a:1,s:"Technical – Algorithms"},
{q:"Which sorting algorithm has the best average-case time complexity?",o:["Bubble Sort","Selection Sort","Merge Sort","Insertion Sort"],a:2,s:"Technical – Algorithms"},
{q:"What does Big-O notation represent?",o:["Best case","Average case","Worst case upper bound","Exact running time"],a:2,s:"Technical – Algorithms"},
{q:"Which algorithmic paradigm is used in the 0/1 Knapsack problem?",o:["Greedy","Divide and Conquer","Dynamic Programming","Brute Force"],a:2,s:"Technical – Algorithms"},

// --- DBMS (Q26-40) ---
{q:"Which normal form eliminates transitive dependency?",o:["1NF","2NF","3NF","BCNF"],a:2,s:"Technical – DBMS"},
{q:"A foreign key in a relational database is used to:",o:["Uniquely identify a row","Reference a primary key in another table","Index a column","Create a view"],a:1,s:"Technical – DBMS"},
{q:"ACID properties in a database stand for:",o:["Atomicity, Consistency, Isolation, Durability","Association, Consistency, Integrity, Durability","Atomicity, Concurrency, Isolation, Durability","Atomicity, Consistency, Isolation, Dependency"],a:0,s:"Technical – DBMS"},
{q:"Which SQL command is used to remove all rows from a table without logging individual row deletions?",o:["DELETE","DROP","TRUNCATE","REMOVE"],a:2,s:"Technical – DBMS"},
{q:"A view in SQL is:",o:["A physical table","A virtual table derived from other tables","A stored procedure","An index"],a:1,s:"Technical – DBMS"},
{q:"Which type of join returns all rows from both tables?",o:["Inner Join","Left Join","Right Join","Full Outer Join"],a:3,s:"Technical – DBMS"},
{q:"Deadlock in DBMS can be prevented by:",o:["Using timestamps","Allowing all requests","Ignoring the problem","Using more memory"],a:0,s:"Technical – DBMS"},
{q:"The SQL clause used to filter groups is:",o:["WHERE","GROUP BY","HAVING","ORDER BY"],a:2,s:"Technical – DBMS"},
{q:"Which of the following is a DDL command?",o:["SELECT","INSERT","ALTER","UPDATE"],a:2,s:"Technical – DBMS"},
{q:"A relation is in BCNF if every determinant is a:",o:["Foreign key","Primary key","Candidate key","Super key"],a:2,s:"Technical – DBMS"},
{q:"What is a trigger in DBMS?",o:["A stored procedure","An automatic action on an event","A type of key","A data type"],a:1,s:"Technical – DBMS"},
{q:"Which type of indexing provides the fastest access for equality searches?",o:["B-tree","Hash","Bitmap","Clustered"],a:1,s:"Technical – DBMS"},
{q:"The two-phase locking protocol ensures:",o:["Deadlock freedom","Serializability","Durability","Atomicity"],a:1,s:"Technical – DBMS"},
{q:"A candidate key is:",o:["A primary key only","Any super key","A minimal super key","A foreign key"],a:2,s:"Technical – DBMS"},
{q:"Which operation in relational algebra selects rows?",o:["Project","Select","Join","Division"],a:1,s:"Technical – DBMS"},

// --- Operating Systems (Q41-52) ---
{q:"Which scheduling algorithm may cause starvation?",o:["FCFS","Round Robin","Shortest Job First","All of the above"],a:2,s:"Technical – Operating Systems"},
{q:"A page fault occurs when:",o:["A page is found in memory","A required page is not in main memory","The page table is full","The disk is full"],a:1,s:"Technical – Operating Systems"},
{q:"The Banker's algorithm is used for:",o:["Memory allocation","Deadlock avoidance","CPU scheduling","Disk scheduling"],a:1,s:"Technical – Operating Systems"},
{q:"Which of the following is NOT a condition for deadlock?",o:["Mutual exclusion","Hold and wait","Preemption","Circular wait"],a:2,s:"Technical – Operating Systems"},
{q:"In a virtual memory system, the page replacement algorithm that results in the minimum number of page faults is:",o:["LRU","FIFO","Optimal","Clock"],a:2,s:"Technical – Operating Systems"},
{q:"A semaphore is used for:",o:["Memory management","Process synchronization","File management","Disk scheduling"],a:1,s:"Technical – Operating Systems"},
{q:"Thrashing occurs when:",o:["CPU utilization is high","A process spends more time paging than executing","Too many processes are in ready queue","The disk is full"],a:1,s:"Technical – Operating Systems"},
{q:"Which memory allocation strategy suffers from external fragmentation?",o:["Paging","Segmentation","Both","Neither"],a:1,s:"Technical – Operating Systems"},
{q:"The purpose of the Translation Lookaside Buffer (TLB) is:",o:["To cache disk blocks","To speed up virtual-to-physical address translation","To store process states","To manage I/O buffers"],a:1,s:"Technical – Operating Systems"},
{q:"Round Robin scheduling is essentially:",o:["Priority scheduling","FCFS with time quantum","SJF with preemption","Multilevel queue"],a:1,s:"Technical – Operating Systems"},
{q:"Which of these is a real-time operating system?",o:["Windows 10","Ubuntu","VxWorks","macOS"],a:2,s:"Technical – Operating Systems"},
{q:"Internal fragmentation occurs in:",o:["Segmentation","Paging","Linked allocation","All of the above"],a:1,s:"Technical – Operating Systems"},

// --- Computer Networks (Q53-65) ---
{q:"The OSI model has how many layers?",o:["5","6","7","4"],a:2,s:"Technical – Computer Networks"},
{q:"Which protocol is used for email transmission?",o:["FTP","SMTP","HTTP","SNMP"],a:1,s:"Technical – Computer Networks"},
{q:"IP address belongs to which class?",o:["Class A","Class B","Class C","Class D"],a:1,s:"Technical – Computer Networks"},
{q:"Which layer of the OSI model is responsible for routing?",o:["Data Link","Transport","Network","Session"],a:2,s:"Technical – Computer Networks"},
{q:"TCP is a:",o:["Connectionless protocol","Connection-oriented protocol","Routing protocol","Application protocol"],a:1,s:"Technical – Computer Networks"},
{q:"The subnet mask 255.255.255.0 indicates how many host bits?",o:["8","16","24","32"],a:0,s:"Technical – Computer Networks"},
{q:"Which device operates at the Data Link layer?",o:["Router","Hub","Switch","Gateway"],a:2,s:"Technical – Computer Networks"},
{q:"ARP is used to map:",o:["IP address to MAC address","MAC address to IP address","Domain name to IP","IP to domain name"],a:0,s:"Technical – Computer Networks"},
{q:"Which protocol provides reliable data transfer?",o:["UDP","TCP","IP","ICMP"],a:1,s:"Technical – Computer Networks"},
{q:"The default port number for HTTP is:",o:["21","25","80","443"],a:2,s:"Technical – Computer Networks"},
{q:"DNS resolves:",o:["IP to MAC address","Domain name to IP address","MAC to IP address","Port to service"],a:1,s:"Technical – Computer Networks"},
{q:"Which topology has a single point of failure at the center?",o:["Bus","Ring","Star","Mesh"],a:2,s:"Technical – Computer Networks"},
{q:"DHCP is used to:",o:["Resolve domain names","Assign IP addresses automatically","Transfer files","Send emails"],a:1,s:"Technical – Computer Networks"},

// --- General Aptitude: Quantitative (Q66-78) ---
{q:"If the cost price of an item is ₹500 and it is sold for ₹600, the profit percentage is:",o:["10%","15%","20%","25%"],a:2,s:"Aptitude – Quantitative"},
{q:"A train 150 m long passes a pole in 15 seconds. Its speed is:",o:["36 km/h","10 km/h","54 km/h","72 km/h"],a:0,s:"Aptitude – Quantitative"},
{q:"The average of first 50 natural numbers is:",o:["25","25.5","26","50"],a:1,s:"Aptitude – Quantitative"},
{q:"If A can do a work in 10 days and B in 15 days, together they can do it in:",o:["5 days","6 days","8 days","12 days"],a:1,s:"Aptitude – Quantitative"},
{q:"The simple interest on ₹5000 at 8% per annum for 3 years is:",o:["₹800","₹1000","₹1200","₹1500"],a:2,s:"Aptitude – Quantitative"},
{q:"A mixture of 40 litres has milk and water in the ratio 3:1. How much water must be added to make the ratio 2:1?",o:["5 litres","6.67 litres","10 litres","15 litres"],a:0,s:"Aptitude – Quantitative"},
{q:"The LCM of 12, 15, and 20 is:",o:["30","60","120","180"],a:1,s:"Aptitude – Quantitative"},
{q:"If 20% of a number is 80, the number is:",o:["200","400","600","160"],a:1,s:"Aptitude – Quantitative"},
{q:"Two pipes can fill a tank in 12 and 18 hours respectively. If both are opened together, the tank is filled in:",o:["6 hours","7.2 hours","8 hours","9 hours"],a:1,s:"Aptitude – Quantitative"},
{q:"The ratio of the ages of A and B is 4:3. After 6 years, the ratio becomes 5:4. The present age of A is:",o:["20 years","24 years","28 years","32 years"],a:1,s:"Aptitude – Quantitative"},
{q:"A car covers 360 km in 6 hours. Its speed in m/s is:",o:["16.67 m/s","60 m/s","100 m/s","36 m/s"],a:0,s:"Aptitude – Quantitative"},
{q:"The compound interest on ₹10,000 at 10% per annum for 2 years is:",o:["₹2000","₹2100","₹2200","₹1900"],a:1,s:"Aptitude – Quantitative"},
{q:"If x + y = 10 and xy = 21, then x² + y² is:",o:["58","42","79","100"],a:0,s:"Aptitude – Quantitative"},

// --- General Aptitude: Reasoning (Q79-88) ---
{q:"In a certain code, COMPUTER is written as RFUVQNPD. How will MEDICINE be written?",o:["EOJDJEFN","NFEJDJOE","FDJDJOFN","MFEJDJOE"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"Find the missing number in the series: 2, 6, 12, 20, 30, ?",o:["40","42","36","48"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"If South-East becomes North, then what does North-East become?",o:["South","West","North-West","South-West"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Pointing to a photograph, a man says 'She is the daughter of my grandfather's only son.' How is the person in the photo related to the man?",o:["Sister","Mother","Daughter","Cousin"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"All roses are flowers. Some flowers are red. Which conclusion is valid?",o:["All roses are red","Some roses are red","Some flowers are roses","No rose is red"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"A is B's sister. C is B's mother. D is C's father. E is D's mother. How is A related to D?",o:["Grandmother","Grandfather","Granddaughter","Daughter"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"If 1st January 2024 is Monday, what day is 1st January 2025?",o:["Tuesday","Wednesday","Thursday","Friday"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Which number replaces the question mark? 3, 9, 27, 81, ?",o:["162","216","243","324"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"In a row of students, Ravi is 12th from the left and 18th from the right. How many students are in the row?",o:["28","29","30","31"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Choose the odd one out: Apple, Mango, Potato, Banana",o:["Apple","Mango","Potato","Banana"],a:2,s:"Aptitude – Logical Reasoning"},

// --- General Aptitude: General Knowledge (Q89-95) ---
{q:"IFFCO stands for:",o:["Indian Farmers Fertiliser Cooperative Limited","Indian Federation of Fertiliser Cooperative","India Farmers Finance Cooperative Limited","Indian Fertiliser and Food Cooperative"],a:0,s:"Aptitude – General Knowledge"},
{q:"IFFCO was established in the year:",o:["1957","1967","1977","1987"],a:1,s:"Aptitude – General Knowledge"},
{q:"The headquarters of IFFCO is located in:",o:["Mumbai","Kolkata","New Delhi","Chennai"],a:2,s:"Aptitude – General Knowledge"},
{q:"Which of the following is a product manufactured by IFFCO?",o:["Steel","Urea","Petroleum","Cement"],a:1,s:"Aptitude – General Knowledge"},
{q:"NITI Aayog replaced which body?",o:["Finance Commission","Planning Commission","Election Commission","Law Commission"],a:1,s:"Aptitude – General Knowledge"},
{q:"The largest cooperative society in the world in terms of turnover is:",o:["Amul","IFFCO","KRIBHCO","NAFED"],a:1,s:"Aptitude – General Knowledge"},
{q:"Article 370 of the Indian Constitution was related to:",o:["Right to Education","Special status of Jammu & Kashmir","Freedom of Speech","Right to Property"],a:1,s:"Aptitude – General Knowledge"},

// --- General Aptitude: English (Q96-100) ---
{q:"Choose the correct synonym of 'Abundant':",o:["Scarce","Plentiful","Meager","Limited"],a:1,s:"Aptitude – English"},
{q:"Identify the error: 'He go to school every day.'",o:["He","go","to school","every day"],a:1,s:"Aptitude – English"},
{q:"Choose the antonym of 'Benevolent':",o:["Kind","Generous","Malevolent","Charitable"],a:2,s:"Aptitude – English"},
{q:"Fill in the blank: She has been working here ___ 2015.",o:["from","since","for","at"],a:1,s:"Aptitude – English"},
{q:"Choose the correctly spelled word:",o:["Accomodation","Acommodation","Accommodation","Acomodation"],a:2,s:"Aptitude – English"}
],

// ====================== MOCK TEST 2 ======================
[
// --- Data Structures (Q1-13) ---
{q:"What is the minimum number of nodes in an AVL tree of height 3?",o:["5","7","4","12"],a:1,s:"Technical – Data Structures"},
{q:"Which data structure is used in BFS of a graph?",o:["Stack","Queue","Tree","Hash Table"],a:1,s:"Technical – Data Structures"},
{q:"The worst-case time complexity of inserting an element at the end of an array of size n is:",o:["O(1)","O(n)","O(log n)","O(n²)"],a:1,s:"Technical – Data Structures"},
{q:"In a doubly linked list, each node has:",o:["One pointer","Two pointers","Three pointers","No pointers"],a:1,s:"Technical – Data Structures"},
{q:"A hash function maps keys to:",o:["Linked lists","Array indices","Trees","Stacks"],a:1,s:"Technical – Data Structures"},
{q:"Which of the following is NOT a self-balancing BST?",o:["AVL Tree","Red-Black Tree","Splay Tree","Binary Heap"],a:3,s:"Technical – Data Structures"},
{q:"The inorder successor of a node in a BST is:",o:["The left child","The parent","The smallest node in the right subtree","The largest node in the left subtree"],a:2,s:"Technical – Data Structures"},
{q:"What data structure is used for Depth-First Search?",o:["Queue","Stack","Heap","Array"],a:1,s:"Technical – Data Structures"},
{q:"The number of leaf nodes in a complete binary tree with n internal nodes is:",o:["n","n-1","n+1","2n"],a:2,s:"Technical – Data Structures"},
{q:"Which of the following has O(1) insertion at the beginning?",o:["Array","Linked List","Binary Tree","Hash Table"],a:1,s:"Technical – Data Structures"},
{q:"A deque supports insertion and deletion at:",o:["Only front","Only rear","Both front and rear","Neither"],a:2,s:"Technical – Data Structures"},
{q:"What is the time complexity of heapify operation?",o:["O(n)","O(n log n)","O(log n)","O(1)"],a:0,s:"Technical – Data Structures"},
{q:"The adjacency matrix representation of a graph uses how much space?",o:["O(V)","O(E)","O(V²)","O(V+E)"],a:2,s:"Technical – Data Structures"},

// --- Algorithms (Q14-25) ---
{q:"Which of the following uses dynamic programming?",o:["Binary Search","Merge Sort","Longest Common Subsequence","DFS"],a:2,s:"Technical – Algorithms"},
{q:"Bellman-Ford algorithm can handle:",o:["Only positive weights","Negative weight edges","Only unweighted graphs","Only directed graphs"],a:1,s:"Technical – Algorithms"},
{q:"The Master Theorem is used to solve:",o:["Linear equations","Recurrence relations","Differential equations","Matrix operations"],a:1,s:"Technical – Algorithms"},
{q:"What is the time complexity of Floyd-Warshall algorithm?",o:["O(V²)","O(V³)","O(VE)","O(V log V)"],a:1,s:"Technical – Algorithms"},
{q:"Greedy algorithm always gives optimal solution for:",o:["0/1 Knapsack","Fractional Knapsack","Travelling Salesman","Graph Coloring"],a:1,s:"Technical – Algorithms"},
{q:"Which of the following is used for pattern matching?",o:["Dijkstra's algorithm","KMP algorithm","Kruskal's algorithm","Prim's algorithm"],a:1,s:"Technical – Algorithms"},
{q:"The time complexity of counting sort is:",o:["O(n log n)","O(n²)","O(n+k)","O(k)"],a:2,s:"Technical – Algorithms"},
{q:"A topological sort is possible only for:",o:["Undirected graphs","Directed Acyclic Graphs","Complete graphs","Cyclic graphs"],a:1,s:"Technical – Algorithms"},
{q:"What is the worst-case time complexity of Radix Sort for n integers with d digits?",o:["O(nd)","O(n log n)","O(n²)","O(d log n)"],a:0,s:"Technical – Algorithms"},
{q:"Which approach does Huffman coding use?",o:["Dynamic Programming","Greedy","Divide and Conquer","Backtracking"],a:1,s:"Technical – Algorithms"},
{q:"The space complexity of DFS using adjacency list is:",o:["O(V)","O(E)","O(V+E)","O(V²)"],a:2,s:"Technical – Algorithms"},
{q:"Which problem can be solved using backtracking?",o:["Shortest path","N-Queens","Minimum spanning tree","Maximum flow"],a:1,s:"Technical – Algorithms"},

// --- DBMS (Q26-37) ---
{q:"Which SQL aggregate function returns the number of rows?",o:["SUM()","AVG()","COUNT()","MAX()"],a:2,s:"Technical – DBMS"},
{q:"A schedule is conflict serializable if it is conflict equivalent to:",o:["Any schedule","A serial schedule","A parallel schedule","A random schedule"],a:1,s:"Technical – DBMS"},
{q:"The GRANT command in SQL is used for:",o:["Creating tables","Giving privileges to users","Deleting records","Updating records"],a:1,s:"Technical – DBMS"},
{q:"Which of the following is a lossless join decomposition requirement?",o:["Common attributes form a key in at least one relation","No common attributes","All attributes in one relation","Foreign keys only"],a:0,s:"Technical – DBMS"},
{q:"A B+ tree is preferred over B tree because:",o:["It uses less space","All data is in leaf nodes","It has fewer levels","It doesn't need balancing"],a:1,s:"Technical – DBMS"},
{q:"Which isolation level in SQL prevents dirty reads but allows non-repeatable reads?",o:["Read Uncommitted","Read Committed","Repeatable Read","Serializable"],a:1,s:"Technical – DBMS"},
{q:"The operation that combines tuples from two relations is:",o:["Select","Project","Join","Union"],a:2,s:"Technical – DBMS"},
{q:"A weak entity depends on:",o:["A foreign key","A strong entity","Another weak entity","An index"],a:1,s:"Technical – DBMS"},
{q:"Which of the following ensures that only valid data is stored in a database?",o:["Triggers","Integrity constraints","Views","Indexes"],a:1,s:"Technical – DBMS"},
{q:"The concept of referential integrity is related to:",o:["Primary key","Foreign key","Candidate key","Super key"],a:1,s:"Technical – DBMS"},
{q:"Which normal form deals with multi-valued dependencies?",o:["3NF","BCNF","4NF","5NF"],a:2,s:"Technical – DBMS"},
{q:"In SQL, which keyword is used to combine results of two SELECT statements?",o:["JOIN","MERGE","UNION","COMBINE"],a:2,s:"Technical – DBMS"},

// --- Operating Systems (Q38-50) ---
{q:"Which of the following is a preemptive scheduling algorithm?",o:["FCFS","SJF (non-preemptive)","Round Robin","Priority (non-preemptive)"],a:2,s:"Technical – Operating Systems"},
{q:"The concept of virtual memory allows:",o:["Programs larger than physical memory to execute","Faster CPU speed","More RAM to be installed","Better disk performance"],a:0,s:"Technical – Operating Systems"},
{q:"Which page replacement algorithm suffers from Belady's anomaly?",o:["LRU","Optimal","FIFO","LFU"],a:2,s:"Technical – Operating Systems"},
{q:"A process in the 'ready' state is waiting for:",o:["I/O completion","CPU allocation","Memory allocation","User input"],a:1,s:"Technical – Operating Systems"},
{q:"The critical section problem requires which of the following?",o:["Mutual exclusion only","Progress and bounded waiting only","Mutual exclusion, progress, and bounded waiting","None of the above"],a:2,s:"Technical – Operating Systems"},
{q:"Which system call creates a new process in Unix?",o:["exec()","fork()","wait()","exit()"],a:1,s:"Technical – Operating Systems"},
{q:"Demand paging means:",o:["All pages are loaded at start","Pages are loaded only when needed","Pages are pre-fetched","Pages are never swapped"],a:1,s:"Technical – Operating Systems"},
{q:"The dispatcher is responsible for:",o:["Scheduling processes","Switching context from one process to another","Managing memory","Handling interrupts"],a:1,s:"Technical – Operating Systems"},
{q:"A zombie process is:",o:["A running process","A process that has terminated but its entry exists in the process table","A blocked process","A suspended process"],a:1,s:"Technical – Operating Systems"},
{q:"Which of the following is true about monolithic kernels?",o:["All OS services run in kernel space","Each service runs in user space","They use microkernel architecture","They are slower than microkernels"],a:0,s:"Technical – Operating Systems"},
{q:"The working set model is related to:",o:["CPU scheduling","Memory management","File systems","Device management"],a:1,s:"Technical – Operating Systems"},
{q:"Spin lock is a type of:",o:["Mutex","Semaphore","Busy waiting lock","Condition variable"],a:2,s:"Technical – Operating Systems"},
{q:"Which of the following scheduling algorithms is best for time-sharing systems?",o:["FCFS","SJF","Round Robin","Priority"],a:2,s:"Technical – Operating Systems"},

// --- Computer Networks (Q51-65) ---
{q:"The transport layer protocol that provides connectionless service is:",o:["TCP","UDP","IP","ICMP"],a:1,s:"Technical – Computer Networks"},
{q:"Which of the following is NOT an application layer protocol?",o:["HTTP","FTP","TCP","DNS"],a:2,s:"Technical – Computer Networks"},
{q:"The maximum data rate of a noiseless channel with bandwidth B and L signal levels is given by:",o:["Shannon's theorem","Nyquist formula","Fourier's theorem","Maxwell's equation"],a:1,s:"Technical – Computer Networks"},
{q:"In IPv4, the header checksum field is:",o:["8 bits","16 bits","32 bits","64 bits"],a:1,s:"Technical – Computer Networks"},
{q:"Which protocol is used to find the MAC address given an IP address?",o:["RARP","ARP","DHCP","DNS"],a:1,s:"Technical – Computer Networks"},
{q:"A hub operates at which layer of the OSI model?",o:["Network","Data Link","Physical","Transport"],a:2,s:"Technical – Computer Networks"},
{q:"The sliding window protocol is used for:",o:["Error detection","Flow control","Routing","Encryption"],a:1,s:"Technical – Computer Networks"},
{q:"What is the maximum number of hosts in a Class C network?",o:["254","256","512","1024"],a:0,s:"Technical – Computer Networks"},
{q:"Which layer handles data encryption and decryption in the OSI model?",o:["Application","Presentation","Session","Transport"],a:1,s:"Technical – Computer Networks"},
{q:"CSMA/CD is used in:",o:["Wi-Fi","Ethernet","Bluetooth","Token Ring"],a:1,s:"Technical – Computer Networks"},
{q:"The TTL field in an IP packet is used to:",o:["Limit the packet's lifetime","Encrypt the packet","Identify the source","Determine the route"],a:0,s:"Technical – Computer Networks"},
{q:"NAT stands for:",o:["Network Address Translation","Network Access Terminal","Node Address Transfer","Network Allocation Table"],a:0,s:"Technical – Computer Networks"},
{q:"Which routing protocol uses the Bellman-Ford algorithm?",o:["OSPF","RIP","BGP","IS-IS"],a:1,s:"Technical – Computer Networks"},
{q:"SSL/TLS operates at which layer?",o:["Network","Transport","Session/Presentation","Application"],a:2,s:"Technical – Computer Networks"},
{q:"What is the size of an IPv6 address?",o:["32 bits","64 bits","128 bits","256 bits"],a:2,s:"Technical – Computer Networks"},

// --- General Aptitude: Quantitative (Q66-78) ---
{q:"The HCF of 36 and 84 is:",o:["6","12","18","24"],a:1,s:"Aptitude – Quantitative"},
{q:"A shopkeeper gives 10% discount and still makes 20% profit. If the cost price is ₹1000, the marked price is:",o:["₹1200","₹1333","₹1400","₹1500"],a:1,s:"Aptitude – Quantitative"},
{q:"If the perimeter of a square is 48 cm, its area is:",o:["144 cm²","96 cm²","192 cm²","64 cm²"],a:0,s:"Aptitude – Quantitative"},
{q:"A boat goes 12 km downstream in 1 hour and 8 km upstream in 1 hour. The speed of the stream is:",o:["2 km/h","4 km/h","6 km/h","10 km/h"],a:0,s:"Aptitude – Quantitative"},
{q:"The value of (15)² - (14)² is:",o:["1","15","29","30"],a:2,s:"Aptitude – Quantitative"},
{q:"In how many ways can 5 people be seated in a row?",o:["25","60","120","720"],a:2,s:"Aptitude – Quantitative"},
{q:"A number when divided by 5 gives remainder 3. When the same number is divided by 4, the remainder is:",o:["Cannot be determined","1","2","3"],a:0,s:"Aptitude – Quantitative"},
{q:"The sum of angles of a hexagon is:",o:["540°","720°","900°","1080°"],a:1,s:"Aptitude – Quantitative"},
{q:"If the diagonal of a square is 10√2 cm, its side is:",o:["5 cm","10 cm","15 cm","20 cm"],a:1,s:"Aptitude – Quantitative"},
{q:"The probability of getting at least one head when two coins are tossed is:",o:["1/4","1/2","3/4","1"],a:2,s:"Aptitude – Quantitative"},
{q:"A does 1/4 of work in 3 days. He finishes the remaining work in:",o:["6 days","9 days","12 days","15 days"],a:1,s:"Aptitude – Quantitative"},
{q:"What is 35% of 400?",o:["120","130","140","150"],a:2,s:"Aptitude – Quantitative"},
{q:"The average of 5 consecutive even numbers starting from 2 is:",o:["4","6","8","10"],a:1,s:"Aptitude – Quantitative"},

// --- General Aptitude: Reasoning (Q79-90) ---
{q:"Complete the series: A, C, F, J, ?",o:["O","N","M","P"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"If FRIEND is coded as HUMGPF, then CANDLE is coded as:",o:["ECPFNG","EAQFNI","ECPFNH","DCQFMG"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"Which figure comes next: 1, 4, 9, 16, 25, ?",o:["30","36","49","64"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"A clock shows 3:15. What is the angle between the hour and minute hands?",o:["0°","7.5°","15°","22.5°"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Statements: All cats are dogs. All dogs are animals. Conclusion: All cats are animals.",o:["True","False","Cannot be determined","Partially true"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"If APPLE = 50, BALL = ?",o:["27","30","33","36"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"In a family, A is the father of B. B is the sister of C. D is the husband of C. How is A related to D?",o:["Brother","Father","Father-in-law","Uncle"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"Find the odd one out: 2, 5, 10, 17, 28, 37",o:["5","10","28","37"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"If January 1, 2000 was Saturday, what day was January 1, 2001?",o:["Sunday","Monday","Tuesday","Wednesday"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"A man walks 5 km North, then 3 km East, then 5 km South. How far is he from the starting point?",o:["3 km","5 km","8 km","13 km"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"Choose the mirror image: d",o:["b","p","q","a"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"Arrange in logical order: 1. Sentence 2. Word 3. Paragraph 4. Letter 5. Chapter",o:["4,2,1,3,5","2,4,1,3,5","4,2,3,1,5","2,1,4,3,5"],a:0,s:"Aptitude – Logical Reasoning"},

// --- General Aptitude: GK & English (Q91-100) ---
{q:"The full form of GST is:",o:["General Sales Tax","Goods and Services Tax","Government Service Tax","Global Standard Tax"],a:1,s:"Aptitude – General Knowledge"},
{q:"Which Indian state has the longest coastline?",o:["Kerala","Tamil Nadu","Gujarat","Maharashtra"],a:2,s:"Aptitude – General Knowledge"},
{q:"Who is known as the 'Father of the Indian Constitution'?",o:["Mahatma Gandhi","Jawaharlal Nehru","B.R. Ambedkar","Sardar Patel"],a:2,s:"Aptitude – General Knowledge"},
{q:"NABARD is associated with the development of:",o:["Heavy industries","Agriculture and rural areas","Urban planning","Information technology"],a:1,s:"Aptitude – General Knowledge"},
{q:"The chemical formula of Urea is:",o:["NH₃","CO(NH₂)₂","NaCl","H₂SO₄"],a:1,s:"Aptitude – General Knowledge"},
{q:"Choose the correct one-word substitution for 'one who knows everything':",o:["Omnipresent","Omniscient","Omnipotent","Omnivore"],a:1,s:"Aptitude – English"},
{q:"Identify the correctly punctuated sentence:",o:["Its a beautiful day.","It's a beautiful day.","Its' a beautiful day.","Its, a beautiful day."],a:1,s:"Aptitude – English"},
{q:"The passive voice of 'She writes a letter' is:",o:["A letter is written by her","A letter was written by her","A letter has been written by her","A letter is being written by her"],a:0,s:"Aptitude – English"},
{q:"Choose the meaning of the idiom 'Break the ice':",o:["Cause damage","Start a conversation","Stop working","Feel cold"],a:1,s:"Aptitude – English"},
{q:"Fill in the blank: Neither the teacher ___ the students were present.",o:["or","nor","and","but"],a:1,s:"Aptitude – English"}
],

// ====================== MOCK TEST 3 ======================
[
// --- Data Structures (Q1-13) ---
{q:"The time complexity of inserting an element in a min-heap is:",o:["O(1)","O(log n)","O(n)","O(n log n)"],a:1,s:"Technical – Data Structures"},
{q:"Which traversal is used to create a copy of a binary tree?",o:["Inorder","Preorder","Postorder","Level order"],a:1,s:"Technical – Data Structures"},
{q:"The maximum number of nodes at level l of a binary tree is:",o:["l","2l","2^l","2^(l+1)"],a:2,s:"Technical – Data Structures"},
{q:"A graph with n vertices and (n-1) edges that is connected is called:",o:["Complete graph","Tree","Bipartite graph","Cycle"],a:1,s:"Technical – Data Structures"},
{q:"Hashing with separate chaining uses:",o:["Arrays only","Linked lists at each bucket","Binary trees at each bucket","Stacks at each bucket"],a:1,s:"Technical – Data Structures"},
{q:"The best case time complexity of Bubble Sort is:",o:["O(n²)","O(n log n)","O(n)","O(1)"],a:2,s:"Technical – Data Structures"},
{q:"In a singly linked list, accessing the kth element takes:",o:["O(1)","O(k)","O(n)","O(log n)"],a:1,s:"Technical – Data Structures"},
{q:"Which of these is NOT an advantage of linked lists over arrays?",o:["Dynamic size","Ease of insertion","Random access","No memory waste"],a:2,s:"Technical – Data Structures"},
{q:"A binary tree with n nodes has how many NULL pointers?",o:["n","n+1","n-1","2n"],a:1,s:"Technical – Data Structures"},
{q:"Which data structure is used in the undo operation of a text editor?",o:["Queue","Stack","Array","Graph"],a:1,s:"Technical – Data Structures"},
{q:"Red-Black trees guarantee which of the following?",o:["O(n) search time","O(log n) search time","O(1) search time","O(n²) search time"],a:1,s:"Technical – Data Structures"},
{q:"The in-degree of a node in a directed graph is:",o:["Number of edges going out","Number of edges coming in","Total edges connected","Number of self-loops"],a:1,s:"Technical – Data Structures"},
{q:"What is the load factor in a hash table?",o:["Number of entries / table size","Table size / entries","Number of collisions","Hash function output"],a:0,s:"Technical – Data Structures"},

// --- Algorithms (Q14-25) ---
{q:"What is the space complexity of iterative binary search?",o:["O(n)","O(log n)","O(1)","O(n log n)"],a:2,s:"Technical – Algorithms"},
{q:"Which of the following algorithms can detect negative weight cycles?",o:["Dijkstra","Bellman-Ford","Floyd-Warshall","Prim's"],a:1,s:"Technical – Algorithms"},
{q:"The time complexity of matrix chain multiplication using dynamic programming is:",o:["O(n²)","O(n³)","O(2ⁿ)","O(n!)"],a:1,s:"Technical – Algorithms"},
{q:"Prim's algorithm starts from:",o:["Any vertex","The vertex with minimum degree","The vertex with maximum degree","A leaf node"],a:0,s:"Technical – Algorithms"},
{q:"Activity Selection Problem is best solved using:",o:["Dynamic Programming","Greedy Algorithm","Backtracking","Divide and Conquer"],a:1,s:"Technical – Algorithms"},
{q:"The lower bound for comparison-based sorting is:",o:["O(n)","O(n log n)","O(n²)","O(log n)"],a:1,s:"Technical – Algorithms"},
{q:"Which of the following is true about BFS?",o:["Uses stack","Finds shortest path in unweighted graph","Cannot handle cycles","Visits leaves first"],a:1,s:"Technical – Algorithms"},
{q:"The Fibonacci series can be computed in O(log n) time using:",o:["Recursion","Memoization","Matrix exponentiation","All of the above"],a:2,s:"Technical – Algorithms"},
{q:"Strassen's matrix multiplication has complexity:",o:["O(n³)","O(n^2.81)","O(n²)","O(n log n)"],a:1,s:"Technical – Algorithms"},
{q:"Which algorithm finds strongly connected components?",o:["Dijkstra's","Prim's","Kosaraju's","Kruskal's"],a:2,s:"Technical – Algorithms"},
{q:"A stable sorting algorithm preserves:",o:["Memory usage","Relative order of equal elements","Time complexity","Space complexity"],a:1,s:"Technical – Algorithms"},
{q:"The recurrence T(n) = T(n-1) + n solves to:",o:["O(n)","O(n log n)","O(n²)","O(2ⁿ)"],a:2,s:"Technical – Algorithms"},

// --- DBMS (Q26-37) ---
{q:"A superkey that contains no redundant attributes is called:",o:["Primary key","Foreign key","Candidate key","Alternate key"],a:2,s:"Technical – DBMS"},
{q:"Which of the following is a DML command?",o:["CREATE","DROP","INSERT","ALTER"],a:2,s:"Technical – DBMS"},
{q:"In the ER model, a diamond shape represents:",o:["Entity","Attribute","Relationship","Key"],a:2,s:"Technical – DBMS"},
{q:"The process of combining two or more relations is called:",o:["Normalization","Denormalization","Decomposition","Aggregation"],a:1,s:"Technical – DBMS"},
{q:"A transaction that has completed successfully is said to be:",o:["Aborted","Committed","Active","Partially committed"],a:1,s:"Technical – DBMS"},
{q:"Which of the following is used for backup and recovery?",o:["Log files","Indexes","Views","Triggers"],a:0,s:"Technical – DBMS"},
{q:"The SQL command to add a new column to a table is:",o:["ADD COLUMN","MODIFY TABLE","ALTER TABLE ... ADD","INSERT COLUMN"],a:2,s:"Technical – DBMS"},
{q:"Functional dependency X → Y means:",o:["Y determines X","X determines Y","X and Y are independent","X and Y are the same"],a:1,s:"Technical – DBMS"},
{q:"A schema defines:",o:["The data stored","The logical structure of the database","The queries","The users"],a:1,s:"Technical – DBMS"},
{q:"Which of the following prevents lost update problem?",o:["Isolation","Atomicity","Durability","Consistency"],a:0,s:"Technical – DBMS"},
{q:"The LIKE operator in SQL is used with:",o:["Numbers only","Wildcard pattern matching","Aggregate functions","JOIN operations"],a:1,s:"Technical – DBMS"},
{q:"Which clause is used to sort the result set in SQL?",o:["GROUP BY","HAVING","ORDER BY","SORT BY"],a:2,s:"Technical – DBMS"},

// --- Operating Systems (Q38-50) ---
{q:"Context switching involves saving the state of:",o:["The CPU only","The current process","The next process","The file system"],a:1,s:"Technical – Operating Systems"},
{q:"Which of the following memory management schemes permits physical address space to be non-contiguous?",o:["Contiguous allocation","Paging","MFT","Single partition"],a:1,s:"Technical – Operating Systems"},
{q:"The ready queue in a system is managed by:",o:["Scheduler","Dispatcher","Memory manager","File system"],a:0,s:"Technical – Operating Systems"},
{q:"A process that is waiting for an I/O event is in:",o:["Running state","Ready state","Waiting/Blocked state","Terminated state"],a:2,s:"Technical – Operating Systems"},
{q:"The page table maps:",o:["Physical to virtual addresses","Virtual to physical addresses","Process to memory","Disk to memory"],a:1,s:"Technical – Operating Systems"},
{q:"Which of the following is NOT a process state?",o:["New","Running","Compiled","Terminated"],a:2,s:"Technical – Operating Systems"},
{q:"RAID 1 provides redundancy through:",o:["Parity","Mirroring","Striping","Compression"],a:1,s:"Technical – Operating Systems"},
{q:"The buddy system is used for:",o:["CPU scheduling","Memory allocation","Disk scheduling","Process synchronization"],a:1,s:"Technical – Operating Systems"},
{q:"Which of the following is a valid file allocation method?",o:["Sequential allocation","Indexed allocation","Linked allocation","All of the above"],a:3,s:"Technical – Operating Systems"},
{q:"A multi-threaded process has:",o:["Multiple PCBs","One thread only","Shared code and data segments among threads","Separate memory for each thread"],a:2,s:"Technical – Operating Systems"},
{q:"The system call used to wait for a child process is:",o:["fork()","exec()","wait()","kill()"],a:2,s:"Technical – Operating Systems"},
{q:"Starvation can be prevented by:",o:["Priority scheduling","Aging","Round Robin","FCFS"],a:1,s:"Technical – Operating Systems"},
{q:"In paging, a logical address is divided into:",o:["Segment number and offset","Page number and offset","Base and limit","Block and sector"],a:1,s:"Technical – Operating Systems"},

// --- Computer Networks (Q51-65) ---
{q:"Which protocol is used to transfer files over the internet?",o:["HTTP","SMTP","FTP","SNMP"],a:2,s:"Technical – Computer Networks"},
{q:"In TCP, a three-way handshake uses which flags?",o:["SYN, ACK, FIN","SYN, SYN-ACK, ACK","SYN, RST, ACK","ACK, FIN, RST"],a:1,s:"Technical – Computer Networks"},
{q:"The maximum segment size in TCP is determined at:",o:["Application layer","Connection establishment","Routing","IP layer"],a:1,s:"Technical – Computer Networks"},
{q:"Which of these is a private IP address range?",o:["192.168.0.0 – 192.168.255.255","200.0.0.0 – 200.255.255.255","8.8.8.0 – 8.8.8.255","172.32.0.0 – 172.63.255.255"],a:0,s:"Technical – Computer Networks"},
{q:"What is the purpose of ICMP?",o:["File transfer","Error reporting and diagnostic functions","Email transmission","Domain resolution"],a:1,s:"Technical – Computer Networks"},
{q:"Congestion control in TCP is handled by:",o:["Sliding window only","Slow start and congestion avoidance","Checksum","TTL"],a:1,s:"Technical – Computer Networks"},
{q:"A VLAN operates at which OSI layer?",o:["Physical","Data Link","Network","Transport"],a:1,s:"Technical – Computer Networks"},
{q:"Which of the following is a connectionless protocol at the Network layer?",o:["TCP","IP","FTP","HTTP"],a:1,s:"Technical – Computer Networks"},
{q:"The purpose of a firewall is:",o:["Speed up internet","Filter incoming and outgoing network traffic","Assign IP addresses","Resolve domain names"],a:1,s:"Technical – Computer Networks"},
{q:"HTTP status code 404 means:",o:["OK","Redirect","Not Found","Server Error"],a:2,s:"Technical – Computer Networks"},
{q:"Which multiplexing technique divides time into slots?",o:["FDM","TDM","WDM","CDM"],a:1,s:"Technical – Computer Networks"},
{q:"OSPF is a:",o:["Distance vector protocol","Link state protocol","Hybrid protocol","Application protocol"],a:1,s:"Technical – Computer Networks"},
{q:"The data rate of Fast Ethernet is:",o:["10 Mbps","100 Mbps","1 Gbps","10 Gbps"],a:1,s:"Technical – Computer Networks"},
{q:"Which layer provides end-to-end communication?",o:["Network","Data Link","Transport","Session"],a:2,s:"Technical – Computer Networks"},
{q:"What is the purpose of a proxy server?",o:["Store DNS records","Act as intermediary for requests","Assign MAC addresses","Encrypt emails"],a:1,s:"Technical – Computer Networks"},

// --- General Aptitude: Quantitative (Q66-78) ---
{q:"If a number is increased by 25%, and then decreased by 20%, the net change is:",o:["0%","5% increase","5% decrease","10% increase"],a:0,s:"Aptitude – Quantitative"},
{q:"The ratio 2:3 is equivalent to:",o:["4:9","6:9","8:9","4:6"],a:1,s:"Aptitude – Quantitative"},
{q:"The volume of a cube with side 5 cm is:",o:["25 cm³","100 cm³","125 cm³","150 cm³"],a:2,s:"Aptitude – Quantitative"},
{q:"A can complete a job in 12 days. B is 60% more efficient than A. B will complete the same job in:",o:["6 days","7.5 days","8 days","10 days"],a:1,s:"Aptitude – Quantitative"},
{q:"What is the next number in the series: 2, 3, 5, 8, 13, ?",o:["18","20","21","23"],a:2,s:"Aptitude – Quantitative"},
{q:"The circumference of a circle with radius 7 cm is: (π = 22/7)",o:["22 cm","44 cm","154 cm","88 cm"],a:1,s:"Aptitude – Quantitative"},
{q:"A discount of 20% on a marked price of ₹500 gives a selling price of:",o:["₹350","₹400","₹450","₹480"],a:1,s:"Aptitude – Quantitative"},
{q:"If the speed of a train is 72 km/h, its speed in m/s is:",o:["10","15","20","25"],a:2,s:"Aptitude – Quantitative"},
{q:"The sum of the interior angles of a triangle is:",o:["90°","180°","270°","360°"],a:1,s:"Aptitude – Quantitative"},
{q:"What is the square root of 1764?",o:["38","40","42","44"],a:2,s:"Aptitude – Quantitative"},
{q:"If log₁₀ 2 = 0.301, then log₁₀ 8 is:",o:["0.602","0.903","2.408","3.01"],a:1,s:"Aptitude – Quantitative"},
{q:"In a class, 60% students passed in English and 70% passed in Maths. If 40% passed in both, what percentage failed in both?",o:["5%","10%","15%","20%"],a:1,s:"Aptitude – Quantitative"},
{q:"Two numbers are in the ratio 3:5 and their difference is 18. The larger number is:",o:["27","30","45","54"],a:2,s:"Aptitude – Quantitative"},

// --- General Aptitude: Reasoning (Q79-88) ---
{q:"If A = 1, B = 2, ..., Z = 26, what is the sum of the letters in 'CAT'?",o:["24","27","30","33"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"Complete the series: Z, X, V, T, ?",o:["S","R","Q","P"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"If WORK is coded as 4-12-9-16, then REST is coded as:",o:["9-22-8-7","13-22-8-7","9-22-7-8","13-22-7-8"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"Find the wrong number: 2, 6, 14, 30, 62, 128",o:["6","14","62","128"],a:3,s:"Aptitude – Logical Reasoning"},
{q:"P is Q's brother. R is Q's mother. S is R's father. T is S's mother. How is P related to T?",o:["Grandson","Great grandson","Grandfather","Son"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Statements: Some books are pens. All pens are pencils. Conclusion: Some books are pencils.",o:["True","False","Uncertain","None"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"A man is facing West. He turns 45° clockwise, then 180° anticlockwise. Which direction is he facing now?",o:["South-East","North-East","South-West","North-West"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"In a class, Ramesh ranks 15th from top and 20th from bottom. How many students are in the class?",o:["33","34","35","36"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Choose the odd one out: Circle, Triangle, Square, Cylinder",o:["Circle","Triangle","Square","Cylinder"],a:3,s:"Aptitude – Logical Reasoning"},
{q:"If × means +, ÷ means −, + means ÷, − means ×, then 12 × 8 ÷ 4 − 2 + 4 = ?",o:["14","16","18","12"],a:2,s:"Aptitude – Logical Reasoning"},

// --- General Aptitude: GK & Current Affairs (Q89-95) ---
{q:"Which is the largest cooperative fertilizer company in India?",o:["KRIBHCO","NFL","IFFCO","RCF"],a:2,s:"Aptitude – General Knowledge"},
{q:"The Digital India initiative was launched in:",o:["2014","2015","2016","2017"],a:1,s:"Aptitude – General Knowledge"},
{q:"Which river is the longest in India?",o:["Yamuna","Godavari","Brahmaputra","Ganga"],a:3,s:"Aptitude – General Knowledge"},
{q:"The Reserve Bank of India was established in:",o:["1925","1935","1945","1955"],a:1,s:"Aptitude – General Knowledge"},
{q:"Which planet is known as the 'Red Planet'?",o:["Venus","Jupiter","Mars","Saturn"],a:2,s:"Aptitude – General Knowledge"},
{q:"The Panchayati Raj system was constitutionalized by which amendment?",o:["71st","72nd","73rd","74th"],a:2,s:"Aptitude – General Knowledge"},
{q:"Make in India initiative focuses on:",o:["Agriculture","Manufacturing","Education","Healthcare"],a:1,s:"Aptitude – General Knowledge"},

// --- General Aptitude: English (Q96-100) ---
{q:"Choose the synonym of 'Inevitable':",o:["Avoidable","Uncertain","Unavoidable","Optional"],a:2,s:"Aptitude – English"},
{q:"Fill in the blank: He insisted ___ going there.",o:["to","for","on","at"],a:2,s:"Aptitude – English"},
{q:"The plural of 'Criterion' is:",o:["Criterions","Criteria","Criterias","Criteriae"],a:1,s:"Aptitude – English"},
{q:"Choose the correct sentence:",o:["He is more taller than me.","He is taller than me.","He is taller than I am.","Both B and C are correct."],a:3,s:"Aptitude – English"},
{q:"The meaning of the idiom 'Burn the midnight oil' is:",o:["Waste resources","Work late into the night","Set something on fire","Travel at night"],a:1,s:"Aptitude – English"}
],

// ====================== MOCK TEST 4 (EASY) ======================
[
// --- Data Structures – Easy (Q1-15) ---
{q:"An array is a collection of elements stored in:",o:["Random locations","Contiguous memory locations","Linked nodes","Stack frames"],a:1,s:"Technical – Data Structures"},
{q:"Which data structure follows LIFO (Last In First Out)?",o:["Queue","Array","Stack","Linked List"],a:2,s:"Technical – Data Structures"},
{q:"Which data structure follows FIFO (First In First Out)?",o:["Stack","Queue","Tree","Graph"],a:1,s:"Technical – Data Structures"},
{q:"A linked list consists of nodes where each node contains:",o:["Only data","Only a pointer","Data and a pointer to the next node","An index"],a:2,s:"Technical – Data Structures"},
{q:"The first element of an array in C/C++ has index:",o:["1","0","-1","Depends on compiler"],a:1,s:"Technical – Data Structures"},
{q:"A binary tree has at most how many children per node?",o:["1","2","3","Unlimited"],a:1,s:"Technical – Data Structures"},
{q:"Which operation adds an element to a stack?",o:["Enqueue","Push","Insert","Add"],a:1,s:"Technical – Data Structures"},
{q:"Which operation removes an element from a queue?",o:["Pop","Dequeue","Delete","Remove"],a:1,s:"Technical – Data Structures"},
{q:"The root is the ___ node of a tree.",o:["Last","Middle","Topmost","Leaf"],a:2,s:"Technical – Data Structures"},
{q:"A leaf node in a tree is a node with:",o:["One child","Two children","No children","Maximum children"],a:2,s:"Technical – Data Structures"},
{q:"Linear search has a time complexity of:",o:["O(1)","O(log n)","O(n)","O(n²)"],a:2,s:"Technical – Data Structures"},
{q:"In a stack, the element that is added last is removed:",o:["Last","First","At random","Never"],a:1,s:"Technical – Data Structures"},
{q:"The size of an array is:",o:["Dynamic by default","Fixed at declaration","Unlimited","Zero"],a:1,s:"Technical – Data Structures"},
{q:"Which of these is a linear data structure?",o:["Tree","Graph","Array","Heap"],a:2,s:"Technical – Data Structures"},
{q:"A string in programming is essentially an array of:",o:["Integers","Characters","Floats","Booleans"],a:1,s:"Technical – Data Structures"},

// --- Algorithms – Easy (Q16-25) ---
{q:"Bubble Sort works by repeatedly:",o:["Dividing the array","Swapping adjacent elements","Inserting elements","Merging arrays"],a:1,s:"Technical – Algorithms"},
{q:"The simplest searching algorithm is:",o:["Binary Search","Hash Search","Linear Search","Jump Search"],a:2,s:"Technical – Algorithms"},
{q:"Binary Search requires the array to be:",o:["Unsorted","Sorted","Empty","Circular"],a:1,s:"Technical – Algorithms"},
{q:"Which of the following is NOT a sorting algorithm?",o:["Bubble Sort","Quick Sort","Linear Search","Merge Sort"],a:2,s:"Technical – Algorithms"},
{q:"An algorithm is a:",o:["Programming language","Step-by-step procedure to solve a problem","Hardware component","Type of data structure"],a:1,s:"Technical – Algorithms"},
{q:"O(1) time complexity means the operation takes:",o:["Linear time","Constant time","Quadratic time","Logarithmic time"],a:1,s:"Technical – Algorithms"},
{q:"Which sorting algorithm picks the minimum element and places it at the beginning?",o:["Bubble Sort","Insertion Sort","Selection Sort","Merge Sort"],a:2,s:"Technical – Algorithms"},
{q:"A flowchart uses ___ to represent decisions:",o:["Rectangles","Diamonds","Circles","Arrows"],a:1,s:"Technical – Algorithms"},
{q:"The process of finding a particular element in an array is called:",o:["Sorting","Searching","Traversing","Hashing"],a:1,s:"Technical – Algorithms"},
{q:"If an array has 10 elements, linear search will take at most ___ comparisons:",o:["1","5","10","100"],a:2,s:"Technical – Algorithms"},

// --- DBMS – Easy (Q26-40) ---
{q:"DBMS stands for:",o:["Data Base Management System","Data Basic Management System","Data Base Manipulation System","Digital Base Management System"],a:0,s:"Technical – DBMS"},
{q:"SQL stands for:",o:["Simple Query Language","Structured Query Language","Standard Query Language","Sequential Query Language"],a:1,s:"Technical – DBMS"},
{q:"Which SQL command is used to retrieve data from a table?",o:["INSERT","UPDATE","SELECT","DELETE"],a:2,s:"Technical – DBMS"},
{q:"A primary key is used to:",o:["Delete records","Uniquely identify each record in a table","Sort data","Create indexes"],a:1,s:"Technical – DBMS"},
{q:"Which SQL command adds new data to a table?",o:["SELECT","INSERT","UPDATE","ALTER"],a:1,s:"Technical – DBMS"},
{q:"A table in a database is also called a:",o:["Query","Relation","Schema","View"],a:1,s:"Technical – DBMS"},
{q:"Which of the following is used to modify existing data in a table?",o:["INSERT","DELETE","UPDATE","SELECT"],a:2,s:"Technical – DBMS"},
{q:"The WHERE clause in SQL is used to:",o:["Sort results","Group results","Filter results based on a condition","Join tables"],a:2,s:"Technical – DBMS"},
{q:"A database is a:",o:["Software program","Organized collection of data","Type of network","Hardware device"],a:1,s:"Technical – DBMS"},
{q:"Which command removes a table from the database?",o:["DELETE","REMOVE","DROP","TRUNCATE"],a:2,s:"Technical – DBMS"},
{q:"In a relational database, data is stored in:",o:["Files","Tables","Graphs","Trees"],a:1,s:"Technical – DBMS"},
{q:"Which SQL keyword removes duplicate rows from results?",o:["UNIQUE","DISTINCT","DIFFERENT","FILTER"],a:1,s:"Technical – DBMS"},
{q:"NULL in SQL means:",o:["Zero","Empty string","Unknown or missing value","False"],a:2,s:"Technical – DBMS"},
{q:"Which SQL clause is used to sort results?",o:["GROUP BY","SORT BY","ORDER BY","ARRANGE BY"],a:2,s:"Technical – DBMS"},
{q:"A row in a table is also called a:",o:["Column","Field","Tuple/Record","Attribute"],a:2,s:"Technical – DBMS"},

// --- Operating Systems – Easy (Q41-52) ---
{q:"An operating system is:",o:["Application software","System software that manages hardware and software","A programming language","A type of database"],a:1,s:"Technical – Operating Systems"},
{q:"Which of these is NOT an operating system?",o:["Windows","Linux","Oracle","macOS"],a:2,s:"Technical – Operating Systems"},
{q:"RAM stands for:",o:["Read Access Memory","Random Access Memory","Readily Available Memory","Run Application Memory"],a:1,s:"Technical – Operating Systems"},
{q:"CPU stands for:",o:["Central Process Unit","Central Processing Unit","Computer Processing Unit","Central Program Unit"],a:1,s:"Technical – Operating Systems"},
{q:"Which of the following is volatile memory?",o:["Hard Disk","SSD","RAM","ROM"],a:2,s:"Technical – Operating Systems"},
{q:"A process is:",o:["A file on disk","A program in execution","A hardware component","An operating system"],a:1,s:"Technical – Operating Systems"},
{q:"Multitasking means:",o:["Running one task at a time","Running multiple tasks concurrently","Running tasks in sequence","Deleting tasks"],a:1,s:"Technical – Operating Systems"},
{q:"The kernel is:",o:["A user application","The core part of an operating system","A type of memory","A programming language"],a:1,s:"Technical – Operating Systems"},
{q:"Which of the following manages files and directories?",o:["CPU","File System","RAM","Compiler"],a:1,s:"Technical – Operating Systems"},
{q:"The main function of an operating system is to:",o:["Run games","Manage computer resources","Write programs","Design hardware"],a:1,s:"Technical – Operating Systems"},
{q:"GUI stands for:",o:["General User Interface","Graphical User Interface","Global Unit Interaction","Graphical Utility Interface"],a:1,s:"Technical – Operating Systems"},
{q:"An example of a mobile operating system is:",o:["Windows 10","Ubuntu","Android","MS-DOS"],a:2,s:"Technical – Operating Systems"},

// --- Computer Networks – Easy (Q53-65) ---
{q:"A computer network is a group of computers that are:",o:["Isolated","Connected to share resources","Turned off","Running the same program"],a:1,s:"Technical – Computer Networks"},
{q:"The Internet is an example of:",o:["LAN","MAN","WAN","PAN"],a:2,s:"Technical – Computer Networks"},
{q:"LAN stands for:",o:["Large Area Network","Local Area Network","Long Area Network","Linked Area Network"],a:1,s:"Technical – Computer Networks"},
{q:"An IP address is used to:",o:["Store data","Identify a device on a network","Run programs","Create files"],a:1,s:"Technical – Computer Networks"},
{q:"HTTP stands for:",o:["HyperText Transfer Protocol","High Text Transfer Program","HyperText Transmission Protocol","Home Text Transfer Protocol"],a:0,s:"Technical – Computer Networks"},
{q:"A router is used to:",o:["Print documents","Connect different networks and forward data","Store data","Display images"],a:1,s:"Technical – Computer Networks"},
{q:"Wi-Fi is a technology for:",o:["Wired internet","Wireless networking","File storage","Email"],a:1,s:"Technical – Computer Networks"},
{q:"Email stands for:",o:["Emergency Mail","Electronic Mail","Express Mail","Encoded Mail"],a:1,s:"Technical – Computer Networks"},
{q:"A web browser is used to:",o:["Write code","Access websites","Create databases","Design hardware"],a:1,s:"Technical – Computer Networks"},
{q:"URL stands for:",o:["Universal Resource Locator","Uniform Resource Locator","United Resource Locator","Universal Reference Link"],a:1,s:"Technical – Computer Networks"},
{q:"Which of these is a web browser?",o:["Microsoft Word","Google Chrome","Photoshop","MySQL"],a:1,s:"Technical – Computer Networks"},
{q:"Bandwidth refers to:",o:["Physical width of a cable","Amount of data transmitted per unit time","Computer speed","Storage capacity"],a:1,s:"Technical – Computer Networks"},
{q:"A firewall is used for:",o:["Heating","Network security","Printing","Programming"],a:1,s:"Technical – Computer Networks"},

// --- Programming Basics (Q66-70) ---
{q:"C language was developed by:",o:["James Gosling","Dennis Ritchie","Bjarne Stroustrup","Guido van Rossum"],a:1,s:"Technical – Programming"},
{q:"Which of these is a valid data type in C?",o:["number","int","string","text"],a:1,s:"Technical – Programming"},
{q:"The output of printf(\"%d\", 5+3); is:",o:["53","8","5+3","Error"],a:1,s:"Technical – Programming"},
{q:"A loop is used to:",o:["Stop a program","Repeat a set of instructions","Declare variables","Print output"],a:1,s:"Technical – Programming"},
{q:"OOP stands for:",o:["Object Oriented Programming","Open Operating Protocol","Ordered Object Process","Original Operating Program"],a:0,s:"Technical – Programming"},

// --- General Aptitude: Quantitative – Easy (Q71-82) ---
{q:"What is 25% of 200?",o:["25","40","50","75"],a:2,s:"Aptitude – Quantitative"},
{q:"If a pen costs ₹10 and you buy 7 pens, the total cost is:",o:["₹17","₹70","₹100","₹77"],a:1,s:"Aptitude – Quantitative"},
{q:"What is the next number: 2, 4, 6, 8, ?",o:["9","10","12","14"],a:1,s:"Aptitude – Quantitative"},
{q:"The area of a rectangle with length 5 and width 3 is:",o:["8","15","16","30"],a:1,s:"Aptitude – Quantitative"},
{q:"What is 144 ÷ 12?",o:["10","11","12","14"],a:2,s:"Aptitude – Quantitative"},
{q:"If a train travels 120 km in 2 hours, its speed is:",o:["30 km/h","60 km/h","120 km/h","240 km/h"],a:1,s:"Aptitude – Quantitative"},
{q:"The square root of 81 is:",o:["7","8","9","10"],a:2,s:"Aptitude – Quantitative"},
{q:"10% of 500 is:",o:["5","10","50","100"],a:2,s:"Aptitude – Quantitative"},
{q:"How many minutes are there in 2 hours?",o:["60","90","120","180"],a:2,s:"Aptitude – Quantitative"},
{q:"If you buy an item for ₹80 and sell it for ₹100, your profit is:",o:["₹10","₹20","₹80","₹100"],a:1,s:"Aptitude – Quantitative"},
{q:"What is the perimeter of a square with side 6 cm?",o:["12 cm","18 cm","24 cm","36 cm"],a:2,s:"Aptitude – Quantitative"},
{q:"The average of 10, 20, and 30 is:",o:["10","15","20","30"],a:2,s:"Aptitude – Quantitative"},

// --- General Aptitude: Reasoning – Easy (Q83-90) ---
{q:"Find the odd one out: Dog, Cat, Cow, Rose",o:["Dog","Cat","Cow","Rose"],a:3,s:"Aptitude – Logical Reasoning"},
{q:"Complete the series: 1, 3, 5, 7, ?",o:["8","9","10","11"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"If Monday comes after Sunday, which day comes after Friday?",o:["Thursday","Saturday","Sunday","Monday"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"How many months have 31 days?",o:["5","6","7","8"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"Complete: AB, CD, EF, ?",o:["FG","GH","HI","IJ"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"If all birds can fly, and a sparrow is a bird, then:",o:["A sparrow cannot fly","A sparrow can fly","Sparrows are not birds","Cannot determine"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Which is the largest: 0.5, 0.05, 0.55, 0.005?",o:["0.5","0.05","0.55","0.005"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"A clock shows 6:00. The angle between the hands is:",o:["90°","120°","150°","180°"],a:3,s:"Aptitude – Logical Reasoning"},

// --- General Aptitude: GK – Easy (Q91-95) ---
{q:"The capital of India is:",o:["Mumbai","Kolkata","New Delhi","Chennai"],a:2,s:"Aptitude – General Knowledge"},
{q:"The national animal of India is:",o:["Lion","Tiger","Elephant","Peacock"],a:1,s:"Aptitude – General Knowledge"},
{q:"India became independent in the year:",o:["1942","1945","1947","1950"],a:2,s:"Aptitude – General Knowledge"},
{q:"The currency of India is:",o:["Dollar","Pound","Rupee","Yen"],a:2,s:"Aptitude – General Knowledge"},
{q:"IFFCO primarily deals with:",o:["Steel","Fertilizers","Textiles","Automobiles"],a:1,s:"Aptitude – General Knowledge"},

// --- General Aptitude: English – Easy (Q96-100) ---
{q:"The plural of 'Child' is:",o:["Childs","Children","Childrens","Childes"],a:1,s:"Aptitude – English"},
{q:"Choose the correct spelling:",o:["Recieve","Recive","Receive","Receeve"],a:2,s:"Aptitude – English"},
{q:"Fill in the blank: She ___ to school every day.",o:["go","goes","going","gone"],a:1,s:"Aptitude – English"},
{q:"The opposite of 'Happy' is:",o:["Glad","Sad","Joyful","Cheerful"],a:1,s:"Aptitude – English"},
{q:"Choose the correct sentence:",o:["He don't know.","He doesn't knows.","He doesn't know.","He not know."],a:2,s:"Aptitude – English"}
]
];
