const MOCK_SET_5 = [
// TECHNICAL (1-100)
{q:"What is the primary function of a reverse proxy?",o:["Load balancing and security","Encrypting databases","Routing internal packets","Compiling source code"],a:0,s:"Technical – Networks"},
{q:"Which of the following is not a NoSQL database type?",o:["Document","Key-Value","Relational","Graph"],a:2,s:"Technical – DBMS"},
{q:"In Git, what does 'git rebase' do?",o:["Moves commits to a new base","Deletes old branches","Creates a new repository","Pushes code to origin"],a:0,s:"Technical – Software Engineering"},
{q:"What is the time complexity of searching in a perfectly balanced Binary Search Tree?",o:["O(1)","O(n)","O(log n)","O(n log n)"],a:2,s:"Technical – DSA"},
{q:"Which HTTP method is idempotent?",o:["POST","PUT","PATCH","CONNECT"],a:1,s:"Technical – Networks"},
{q:"What is a 'race condition' in OS?",o:["When threads compete for resources causing unpredictable behavior","When CPU runs too fast","When memory is full","When a process is killed"],a:0,s:"Technical – OS"},
{q:"Which sorting algorithm uses a pivot element?",o:["Merge Sort","Bubble Sort","Quick Sort","Insertion Sort"],a:2,s:"Technical – DSA"},
{q:"What does ACID stand for in databases?",o:["Atomicity, Consistency, Isolation, Durability","Automatic, Concurrent, Indexed, Distributed","Atomicity, Concurrency, Isolation, Durability","Asynchronous, Consistent, Isolated, Distributed"],a:0,s:"Technical – DBMS"},
{q:"What is a dangling pointer?",o:["A pointer that points to freed memory","A pointer without a type","A pointer pointing to a global variable","A pointer that is null"],a:0,s:"Technical – DSA"},
{q:"Which design pattern ensures only one instance of a class is created?",o:["Factory","Observer","Singleton","Decorator"],a:2,s:"Technical – Software Engineering"},
{q:"What is the purpose of B-trees?",o:["Optimizing disk reads","Sorting strings","Networking routing","Memory allocation"],a:0,s:"Technical – DBMS"},
{q:"Which OSI layer handles routing?",o:["Data Link","Network","Transport","Application"],a:1,s:"Technical – Networks"},
{q:"What is the difference between a mutex and a semaphore?",o:["Mutex is for locking, semaphore is for signaling","They are exactly the same","Mutex is hardware, semaphore is software","Semaphore is faster"],a:0,s:"Technical – OS"},
{q:"What does 'normalization' achieve in databases?",o:["Increases redundancy","Reduces data redundancy","Increases storage size","Adds more tables randomly"],a:1,s:"Technical – DBMS"},
{q:"What is the default port for HTTPS?",o:["80","443","22","21"],a:1,s:"Technical – Networks"},
{q:"In Big O notation, what is O(1)?",o:["Linear time","Constant time","Quadratic time","Logarithmic time"],a:1,s:"Technical – DSA"},
{q:"What is thrashing in OS?",o:["Excessive page faulting causing low CPU utilization","High CPU utilization","Fast memory access","Disk formatting"],a:0,s:"Technical – OS"},
{q:"What is polymorphism in OOP?",o:["Hiding data","Inheriting from multiple classes","Ability to take many forms","Creating multiple objects"],a:2,s:"Technical – Programming"},
{q:"Which scheduling algorithm gives the minimum average waiting time?",o:["FCFS","Round Robin","Shortest Job First","Priority Scheduling"],a:2,s:"Technical – OS"},
{q:"What is a foreign key?",o:["A key that uniquely identifies a row","A key in one table that points to a primary key in another","A key used for encryption","A key assigned by the OS"],a:1,s:"Technical – DBMS"},
{q:"What is the primary benefit of microservices?",o:["Easier to deploy monoliths","Independent scalability and deployment","Shared database for all services","Slower execution"],a:1,s:"Technical – Software Engineering"},
{q:"Which tree traversal visits the root node last?",o:["Pre-order","In-order","Post-order","Level-order"],a:2,s:"Technical – DSA"},
{q:"What is the TCP 3-way handshake?",o:["SYN, SYN-ACK, ACK","ACK, SYN, SYN-ACK","SYN, ACK, FIN","FIN, ACK, SYN"],a:0,s:"Technical – Networks"},
{q:"What does a compiler do?",o:["Executes code line by line","Translates high-level language to machine code","Debugs code automatically","Manages memory"],a:1,s:"Technical – Programming"},
{q:"What is the main function of the ARP protocol?",o:["Resolve IP to MAC address","Resolve MAC to IP address","Route packets","Encrypt data"],a:0,s:"Technical – Networks"},
{q:"Which data structure uses LIFO?",o:["Queue","Stack","Tree","Graph"],a:1,s:"Technical – DSA"},
{q:"What is a left outer join?",o:["Returns all rows from the right table","Returns all rows from both tables","Returns all rows from the left table and matched rows from right","Returns only unmatched rows"],a:2,s:"Technical – DBMS"},
{q:"What is virtual memory?",o:["RAM installed on the motherboard","An illusion of a large main memory","Cache memory","Registers"],a:1,s:"Technical – OS"},
{q:"What is the purpose of DNS?",o:["Translate domain names to IP addresses","Assign IP addresses","Encrypt web traffic","Host websites"],a:0,s:"Technical – Networks"},
{q:"What is encapsulation?",o:["Binding data and methods together","Reusing code","Creating multiple forms","Hiding the entire class"],a:0,s:"Technical – Programming"},
{q:"Which algorithm is used for finding the shortest path in a graph?",o:["Dijkstra's","Merge Sort","Binary Search","Kruskal's"],a:0,s:"Technical – DSA"},
{q:"What is a view in SQL?",o:["A physical table","A virtual table based on a query","A database user","A stored procedure"],a:1,s:"Technical – DBMS"},
{q:"What is agile methodology?",o:["Sequential design process","Iterative and incremental development","No planning approach","Hardware design methodology"],a:1,s:"Technical – Software Engineering"},
{q:"What is context switching?",o:["Switching user accounts","Switching the CPU from one process to another","Switching between RAM and ROM","Switching programming languages"],a:1,s:"Technical – OS"},
{q:"Which IP address is loopback?",o:["192.168.1.1","127.0.0.1","255.255.255.0","10.0.0.1"],a:1,s:"Technical – Networks"},
{q:"What is dynamic programming?",o:["Programming with dynamic typing","Solving complex problems by breaking them down into simpler subproblems","Writing code quickly","Using dynamic arrays"],a:1,s:"Technical – DSA"},
{q:"What is a deadlock?",o:["A process is sleeping","Two or more processes are waiting indefinitely for an event","System shutdown","CPU overheating"],a:1,s:"Technical – OS"},
{q:"What is the difference between TRUNCATE and DELETE?",o:["TRUNCATE is DML, DELETE is DDL","TRUNCATE is faster and cannot be rolled back","DELETE cannot have a WHERE clause","They are exactly the same"],a:1,s:"Technical – DBMS"},
{q:"What is a heap data structure primarily used for?",o:["Sorting strings","Priority queues","Networking","Graph traversal"],a:1,s:"Technical – DSA"},
{q:"What does REST stand for?",o:["Representational State Transfer","Random Execution State Transfer","Remote Execute System Tool","Routing Element State Transfer"],a:0,s:"Technical – Networks"},
{q:"What is inheritance in OOP?",o:["Hiding data","A class deriving properties from another class","Function overloading","Creating an interface"],a:1,s:"Technical – Programming"},
{q:"What is page replacement in OS?",o:["Swapping pages from disk to memory when memory is full","Replacing damaged RAM","Formatting the hard drive","Changing web pages"],a:0,s:"Technical – OS"},
{q:"Which normal form deals with multi-valued dependencies?",o:["1NF","2NF","3NF","4NF"],a:3,s:"Technical – DBMS"},
{q:"What is a graph in data structures?",o:["A bar chart","A collection of nodes and edges","A binary tree","A linked list"],a:1,s:"Technical – DSA"},
{q:"What is the role of a router?",o:["Connect devices in a LAN","Forward data packets between computer networks","Provide Wi-Fi","Store data"],a:1,s:"Technical – Networks"},
{q:"What is continuous integration (CI)?",o:["Merging code to a shared repository frequently","Deploying to production directly","Writing code without testing","Manual deployment"],a:0,s:"Technical – Software Engineering"},
{q:"What is a thread?",o:["A separate program","A lightweight process","A hardware component","A network connection"],a:1,s:"Technical – OS"},
{q:"What is SQL injection?",o:["Adding SQL to a resume","A code injection technique used to attack data-driven applications","Optimizing SQL queries","Backing up a database"],a:1,s:"Technical – DBMS"},
{q:"What is the worst-case time complexity of Quick Sort?",o:["O(n)","O(n log n)","O(n^2)","O(log n)"],a:2,s:"Technical – DSA"},
{q:"What is NAT?",o:["Network Address Translation","National Access Tool","Node Allocation Table","Network Array Type"],a:0,s:"Technical – Networks"},
{q:"What is an abstract class?",o:["A class with no methods","A class that cannot be instantiated","A class with only variables","A final class"],a:1,s:"Technical – Programming"},
{q:"What is spooling?",o:["Sending emails","Simultaneous Peripheral Operations On-line","Speeding up CPU","Storing passwords"],a:1,s:"Technical – OS"},
{q:"What is a primary key?",o:["Any column in a table","A column that uniquely identifies a row","A column that allows nulls","A column used for indexing only"],a:1,s:"Technical – DBMS"},
{q:"What is the purpose of a hash table?",o:["Sorting data","Fast data retrieval using a key","Creating graphs","Storing large files"],a:1,s:"Technical – DSA"},
{q:"What is the TCP window size?",o:["Size of the monitor","Amount of data that can be sent without acknowledgment","Size of a packet","Speed of the connection"],a:1,s:"Technical – Networks"},
{q:"What is unit testing?",o:["Testing the whole system","Testing individual components or functions","Testing network speed","User acceptance testing"],a:1,s:"Technical – Software Engineering"},
{q:"What is a semaphore?",o:["A signaling mechanism to control access to a common resource","A hardware lock","A network protocol","A database index"],a:0,s:"Technical – OS"},
{q:"What is a stored procedure?",o:["A physical file","A pre-compiled SQL code that can be reused","A table alias","A database user"],a:1,s:"Technical – DBMS"},
{q:"What is an AVL tree?",o:["A binary search tree","A self-balancing binary search tree","A graph","A heap"],a:1,s:"Technical – DSA"},
{q:"What is the difference between IPv4 and IPv6?",o:["IPv6 is 32-bit, IPv4 is 128-bit","IPv4 is 32-bit, IPv6 is 128-bit","They are the same","IPv4 is faster"],a:1,s:"Technical – Networks"},
{q:"What is an interface in Java?",o:["A class with implemented methods","A blueprint of a class containing abstract methods","A graphical user interface","A variable type"],a:1,s:"Technical – Programming"},
{q:"What is the bootloader?",o:["A program that loads the OS into memory","A virus","A web browser","A compiler"],a:0,s:"Technical – OS"},
{q:"What is an index in a database?",o:["A table column","A data structure that improves the speed of data retrieval operations","A primary key","A foreign key"],a:1,s:"Technical – DBMS"},
{q:"What is a linked list?",o:["A linear collection of data elements whose order is not given by their physical placement in memory","An array","A tree","A stack"],a:0,s:"Technical – DSA"},
{q:"What is DHCP?",o:["Dynamic Host Configuration Protocol","Data Handling Control Protocol","Domain Host Control Program","Dynamic Hardware Configuration Protocol"],a:0,s:"Technical – Networks"},
{q:"What is version control?",o:["Managing different versions of software code","Controlling network speed","Updating OS","Managing databases"],a:0,s:"Technical – Software Engineering"},
{q:"What is a kernel?",o:["A hardware component","The core component of an OS that manages system resources","A web server","A programming language"],a:1,s:"Technical – OS"},
{q:"What is a transaction in SQL?",o:["A single SQL query","A unit of work that is either completed entirely or not at all","A database backup","A network request"],a:1,s:"Technical – DBMS"},
{q:"What is the time complexity of binary search?",o:["O(n)","O(1)","O(log n)","O(n^2)"],a:2,s:"Technical – DSA"},
{q:"What is a subnet mask?",o:["Hides the IP address","Divides an IP address into network and host addresses","Encrypts data","Connects networks"],a:1,s:"Technical – Networks"},
{q:"What is a constructor?",o:["A method used to destroy objects","A special method used to initialize objects","A variable","A class"],a:1,s:"Technical – Programming"},
{q:"What is pagination in OS?",o:["Creating web pages","A memory management scheme that eliminates the need for contiguous allocation of physical memory","Printing documents","Sorting files"],a:1,s:"Technical – OS"},
{q:"What is a commit in a database?",o:["Discarding changes","Saving all changes made in the current transaction permanently","Creating a table","Deleting a row"],a:1,s:"Technical – DBMS"},
{q:"What is an adjacency matrix?",o:["A 2D array used to represent a graph","A linked list","A hash table","A tree"],a:0,s:"Technical – DSA"},
{q:"What is the ping command used for?",o:["Testing connectivity between two nodes","Downloading files","Formatting disk","Creating a network"],a:0,s:"Technical – Networks"},
{q:"What is a sprint in Agile?",o:["A fast network connection","A set period of time during which specific work has to be completed and made ready for review","A quick meeting","A software bug"],a:1,s:"Technical – Software Engineering"},
{q:"What is a shell?",o:["A hardware component","A user interface for access to an operating system's services","A database table","A network protocol"],a:1,s:"Technical – OS"},
{q:"What is a trigger in SQL?",o:["A manual function","A special type of stored procedure that automatically runs when an event occurs in the database server","A primary key","An index"],a:1,s:"Technical – DBMS"},
{q:"What is a stack overflow?",o:["A website","When a program attempts to use more space than is available on the call stack","When a queue is full","A network error"],a:1,s:"Technical – DSA"},
{q:"What is a firewall?",o:["A hardware or software network security system that monitors and controls incoming and outgoing network traffic","A virus","A web browser","A database"],a:0,s:"Technical – Networks"},
{q:"What is method overloading?",o:["Methods with the same name but different parameters","Methods with different names","A method calling itself","A method overriding a parent method"],a:0,s:"Technical – Programming"},
{q:"What is an interrupt?",o:["A signal to the processor emitted by hardware or software indicating an event that needs immediate attention","A power failure","A network disconnection","A syntax error"],a:0,s:"Technical – OS"},
{q:"What is data redundancy?",o:["Data compression","The same piece of data is held in two separate places","Data encryption","Data deletion"],a:1,s:"Technical – DBMS"},
{q:"What is a trie?",o:["A binary tree","A tree-like data structure used for locating specific keys from within a set","A graph","A queue"],a:1,s:"Technical – DSA"},
{q:"What is a MAC address?",o:["An IP address","A unique identifier assigned to a network interface controller for use as a network address in communications within a network segment","A domain name","A routing protocol"],a:1,s:"Technical – Networks"},
{q:"What is a use case diagram?",o:["A diagram showing the flow of control","A representation of a user's interaction with the system","A database schema","A network topology"],a:1,s:"Technical – Software Engineering"},
{q:"What is a process control block (PCB)?",o:["A hardware circuit","A data structure in the operating system kernel containing the information needed to manage a particular process","A network packet","A database index"],a:1,s:"Technical – OS"},
{q:"What is an entity in ER modeling?",o:["A relationship","A real-world object or concept","An attribute","A query"],a:1,s:"Technical – DBMS"},
{q:"What is a minimum spanning tree?",o:["A tree with the maximum weight","A subset of the edges of a connected, edge-weighted undirected graph that connects all the vertices together, without any cycles and with the minimum possible total edge weight","A binary search tree","A balanced tree"],a:1,s:"Technical – DSA"},
{q:"What is the BGP protocol?",o:["Border Gateway Protocol","Basic Gateway Protocol","Border Group Protocol","Binary Gateway Protocol"],a:0,s:"Technical – Networks"},
{q:"What is an exception in programming?",o:["A syntax error","An event that disrupts the normal flow of the program's instructions","A successful execution","A variable declaration"],a:1,s:"Technical – Programming"},
{q:"What is a monolithic architecture?",o:["An architecture composed of small independent services","A unified model in which the user interface and data access code are combined into a single program from a single platform","A hardware design","A database structure"],a:1,s:"Technical – Software Engineering"},
{q:"What is a context switch overhead?",o:["The time it takes to boot the OS","The time spent by the OS switching between processes, during which no useful work is done","The time to load a web page","The time to query a database"],a:1,s:"Technical – OS"},
{q:"What is a composite key?",o:["A single column primary key","A primary key composed of multiple columns","A foreign key","An index"],a:1,s:"Technical – DBMS"},
{q:"What is the knapsack problem an example of?",o:["Sorting","Dynamic programming or greedy algorithms","Graph traversal","String matching"],a:1,s:"Technical – DSA"},
{q:"What is SNMP?",o:["Simple Network Management Protocol","Secure Network Management Protocol","Standard Network Management Protocol","Simple Node Management Protocol"],a:0,s:"Technical – Networks"},
{q:"What is a design pattern?",o:["A specific piece of code","A general repeatable solution to a commonly occurring problem in software design","A network topology","A database schema"],a:1,s:"Technical – Software Engineering"},
{q:"What is a GUI?",o:["General User Interface","Graphical User Interface","Graphical User Integration","General User Integration"],a:1,s:"Technical – OS"},
{q:"What is data integrity?",o:["Data encryption","The maintenance of, and the assurance of, the accuracy and consistency of data over its entire life-cycle","Data backup","Data deletion"],a:1,s:"Technical – DBMS"},
{q:"What is a queue?",o:["First In First Out (FIFO) data structure","Last In First Out (LIFO) data structure","A non-linear data structure","A tree"],a:0,s:"Technical – DSA"},

// APTITUDE & GENERAL (101-150)
{q:"If a train 120 meters long passes a telegraph post in 6 seconds, what is its speed?",o:["72 km/hr","60 km/hr","80 km/hr","90 km/hr"],a:0,s:"Aptitude – Quantitative"},
{q:"Find the next number in the series: 2, 6, 12, 20, 30, ...",o:["40","42","44","46"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Who is the current Secretary-General of the United Nations (as of 2026)?",o:["Ban Ki-moon","Kofi Annan","António Guterres","Boutros Boutros-Ghali"],a:2,s:"Aptitude – General Knowledge"},
{q:"Choose the synonym for 'Ephemeral':",o:["Permanent","Short-lived","Beautiful","Heavy"],a:1,s:"Aptitude – English"},
{q:"A sum of money doubles itself in 10 years at simple interest. What is the rate of interest?",o:["5%","10%","15%","20%"],a:1,s:"Aptitude – Quantitative"},
{q:"If A is the brother of B; B is the sister of C; and C is the father of D, how is D related to A?",o:["Nephew/Niece","Brother","Cousin","Uncle"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"Which planet is known as the Red Planet?",o:["Venus","Jupiter","Mars","Saturn"],a:2,s:"Aptitude – General Knowledge"},
{q:"Select the correct spelling:",o:["Accomodation","Accommodation","Acommodation","Accomodation"],a:1,s:"Aptitude – English"},
{q:"If 15 men can do a piece of work in 20 days, in how many days can 10 men do it?",o:["30 days","25 days","40 days","35 days"],a:0,s:"Aptitude – Quantitative"},
{q:"If 'APPLE' is coded as 'EQTPI', how is 'MANGO' coded?",o:["QERKS","QDRKS","QERLS","PDRKS"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"What is the capital of Australia?",o:["Sydney","Melbourne","Canberra","Perth"],a:2,s:"Aptitude – General Knowledge"},
{q:"Choose the antonym for 'Obscure':",o:["Clear","Hidden","Dark","Confusing"],a:0,s:"Aptitude – English"},
{q:"A shopkeeper sells an article at a 10% loss. If he had sold it for Rs. 50 more, he would have gained 10%. What is the cost price?",o:["Rs. 200","Rs. 250","Rs. 300","Rs. 350"],a:1,s:"Aptitude – Quantitative"},
{q:"Find the odd one out: Circle, Square, Triangle, Sphere",o:["Circle","Square","Triangle","Sphere"],a:3,s:"Aptitude – Logical Reasoning"},
{q:"Who wrote the play 'Hamlet'?",o:["Charles Dickens","William Shakespeare","Jane Austen","Mark Twain"],a:1,s:"Aptitude – General Knowledge"},
{q:"Fill in the blank: She is good ___ playing the piano.",o:["in","at","on","with"],a:1,s:"Aptitude – English"},
{q:"The LCM of two numbers is 48 and their HCF is 8. If one number is 16, what is the other?",o:["24","32","40","48"],a:0,s:"Aptitude – Quantitative"},
{q:"Pointing to a photograph, a man said, 'I have no brother or sister, but that man's father is my father's son.' Whose photograph was it?",o:["His own","His son's","His father's","His grandfather's"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Which is the longest river in the world?",o:["Amazon","Nile","Yangtze","Mississippi"],a:1,s:"Aptitude – General Knowledge"},
{q:"Identify the error: 'The team are playing well.'",o:["No error","The team","are playing","well"],a:2,s:"Aptitude – English"},
{q:"What is the probability of getting a sum of 7 when two dice are thrown?",o:["1/6","1/12","1/36","1/8"],a:0,s:"Aptitude – Quantitative"},
{q:"Arrange the words in a logical sequence: 1. Seed 2. Plant 3. Tree 4. Fruit",o:["1, 2, 3, 4","1, 3, 2, 4","2, 1, 3, 4","4, 3, 2, 1"],a:0,s:"Aptitude – Logical Reasoning"},
{q:"What is the chemical symbol for Gold?",o:["Ag","Au","Go","Gd"],a:1,s:"Aptitude – General Knowledge"},
{q:"Choose the correct meaning of the idiom: 'To spill the beans'",o:["To drop food","To reveal a secret","To act clumsy","To cook a meal"],a:1,s:"Aptitude – English"},
{q:"If the perimeter of a square is 40 cm, what is its area?",o:["100 sq cm","80 sq cm","40 sq cm","160 sq cm"],a:0,s:"Aptitude – Quantitative"},
{q:"In a certain code, '123' means 'hot filtered coffee', '356' means 'very hot day' and '589' means 'day and night'. Which digit means 'very'?",o:["5","6","8","9"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Which country is known as the Land of the Rising Sun?",o:["China","Japan","South Korea","Thailand"],a:1,s:"Aptitude – General Knowledge"},
{q:"Change to passive voice: 'He writes a letter.'",o:["A letter is written by him.","A letter was written by him.","He is writing a letter.","A letter has been written by him."],a:0,s:"Aptitude – English"},
{q:"The average of 5 numbers is 20. If one number is excluded, the average becomes 18. What is the excluded number?",o:["28","30","22","26"],a:0,s:"Aptitude – Quantitative"},
{q:"SCD, TEF, UGH, ____, WKL",o:["CMN","UJI","VIJ","IJT"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"Who is the author of 'The Discovery of India'?",o:["Mahatma Gandhi","Jawaharlal Nehru","Sardar Patel","Bhagat Singh"],a:1,s:"Aptitude – General Knowledge"},
{q:"Select the one which best expresses the meaning of the given word: 'ABUNDANT'",o:["Plentiful","Scarce","Small","Rare"],a:0,s:"Aptitude – English"},
{q:"A can do a work in 15 days and B in 20 days. If they work on it together for 4 days, what fraction of the work is left?",o:["8/15","7/15","1/4","1/2"],a:0,s:"Aptitude – Quantitative"},
{q:"What comes next in the sequence: A, C, F, J, O, ...",o:["T","U","V","W"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"What is the largest ocean on Earth?",o:["Atlantic Ocean","Indian Ocean","Arctic Ocean","Pacific Ocean"],a:3,s:"Aptitude – General Knowledge"},
{q:"Fill in the blank: He is ___ honest man.",o:["a","an","the","no article"],a:1,s:"Aptitude – English"},
{q:"If the price of a book is increased by 20% and then decreased by 20%, what is the net change?",o:["No change","4% increase","4% decrease","10% decrease"],a:2,s:"Aptitude – Quantitative"},
{q:"If SOUTH-EAST becomes NORTH, NORTH-EAST becomes WEST and so on. What will WEST become?",o:["SOUTH-WEST","SOUTH-EAST","NORTH-WEST","SOUTH"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Which gas is most abundant in the Earth's atmosphere?",o:["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],a:2,s:"Aptitude – General Knowledge"},
{q:"Find the correctly spelt word:",o:["Ocurrence","Occurrence","Occurence","Occurrance"],a:1,s:"Aptitude – English"},
{q:"The ratio of ages of two persons is 4:7 and the age of one of them is greater than the age of the other by 30 years. The sum of their ages is:",o:["100","110","120","130"],a:1,s:"Aptitude – Quantitative"},
{q:"Identify the next term: 3, 9, 27, 81, ...",o:["162","243","324","200"],a:1,s:"Aptitude – Logical Reasoning"},
{q:"Who invented the World Wide Web?",o:["Steve Jobs","Bill Gates","Tim Berners-Lee","Mark Zuckerberg"],a:2,s:"Aptitude – General Knowledge"},
{q:"Complete the sentence: If I ___ rich, I would travel the world.",o:["was","am","were","have been"],a:2,s:"Aptitude – English"},
{q:"A train 150m long is running with a speed of 68 kmph. In what time will it pass a man who is running at 8 kmph in the same direction?",o:["9 sec","10 sec","12 sec","15 sec"],a:0,s:"Aptitude – Quantitative"},
{q:"Which word does NOT belong with the others?",o:["Leopard","Cougar","Elephant","Lion"],a:2,s:"Aptitude – Logical Reasoning"},
{q:"What is the hardest natural substance on Earth?",o:["Gold","Iron","Diamond","Platinum"],a:2,s:"Aptitude – General Knowledge"},
{q:"Choose the correct one word substitution: 'A person who loves books'",o:["Bibliophile","Philanthropist","Misogynist","Optimist"],a:0,s:"Aptitude – English"},
{q:"What is 15% of 60?",o:["8","9","10","12"],a:1,s:"Aptitude – Quantitative"},
{q:"If 1 = 3, 2 = 3, 3 = 5, 4 = 4, 5 = 4, then 6 = ?",o:["3","4","5","6"],a:0,s:"Aptitude – Logical Reasoning"}
];

// Append to the existing sets globally
if (typeof ALL_MOCK_SETS !== 'undefined') {
    ALL_MOCK_SETS.push(MOCK_SET_5);
}
